# config/chewy.yml
# separate environment configs
test:
  host:  'https://ouk1qw6yd8:u4uox7bo4o@spruce-528688837.us-east-1.bonsaisearch.net/'
  prefix: 'test'
development:
  host: 'https://ouk1qw6yd8:u4uox7bo4o@spruce-528688837.us-east-1.bonsaisearch.net/'
